# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IG2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import IG1 as G1
import IG3 as G3
import IG4 as G4
from Clases.Usuario import Usuario
import os

class Ui_IG2_MenuUsuario(object):
    def setupUi(self, IG2_MenuUsuario):
        IG2_MenuUsuario.setObjectName("IG2_MenuUsuario")
        IG2_MenuUsuario.resize(500, 320)
        font = QtGui.QFont()
        font.setFamily("Croissant One")
        font.setPointSize(10)
        IG2_MenuUsuario.setFont(font)
        IG2_MenuUsuario.setStyleSheet("QWidget{\n"
                                      "background-color: rgb(255, 175, 247);\n"
                                      "}\n"
                                      "")
        self.gridLayout = QtWidgets.QGridLayout(IG2_MenuUsuario)
        self.gridLayout.setObjectName("gridLayout")
        self.botonAprender = QtWidgets.QPushButton(IG2_MenuUsuario)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botonAprender.setFont(font)
        self.botonAprender.setStyleSheet("QPushButton{\n"
                                         "color: rgb(255, 255, 255);\n"
                                         "    background-color: rgb(46, 165, 255);\n"
                                         "    font: 12pt \"Segoe Print\";\n"
                                         "    border-radius: 11px;\n"
                                         "    border:none;\n"
                                         "    border-left: 1px solid rgb(44, 131, 212);\n"
                                         "    border-right: 1px solid rgb(44, 131, 212);\n"
                                         "    border-bottom: 3px solid rgb(44, 131, 212);\n"
                                         "}\n"
                                         "QPushButton:hover{\n"
                                         "    background-color: rgb(14, 235, 255);\n"
                                         "    border-left: 1px solid rgb(44, 131, 212);\n"
                                         "    border-right: 1px solid rgb(44, 131, 212);\n"
                                         "    border-bottom: 3px solid rgb(44, 131, 212);\n"
                                         "}\n"
                                         "QPushButton:pressed{\n"
                                         "    background-color: rgb(40, 170, 221);\n"
                                         "    border-left: 1px solid rgb(44, 131, 212);\n"
                                         "    border-right: 1px solid rgb(44, 131, 212);\n"
                                         "    border-top: 3px solid rgb(44, 131, 212);\n"
                                         "    border-bottomr: none;\n"
                                         "}")
        self.botonAprender.setObjectName("botonAprender")
        self.gridLayout.addWidget(self.botonAprender, 3, 3, 1, 1)
        self.botonRegresarInicio = QtWidgets.QPushButton(IG2_MenuUsuario)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botonRegresarInicio.setFont(font)
        self.botonRegresarInicio.setStyleSheet("QPushButton{\n"
                                               "color: rgb(255, 255, 255);\n"
                                               "    background-color: rgb(46, 165, 255);\n"
                                               "    font: 12pt \"Segoe Print\";\n"
                                               "    border-radius: 11px;\n"
                                               "    border:none;\n"
                                               "    border-left: 1px solid rgb(44, 131, 212);\n"
                                               "    border-right: 1px solid rgb(44, 131, 212);\n"
                                               "    border-bottom: 3px solid rgb(44, 131, 212);\n"
                                               "}\n"
                                               "QPushButton:hover{\n"
                                               "    background-color: rgb(14, 235, 255);\n"
                                               "    border-left: 1px solid rgb(44, 131, 212);\n"
                                               "    border-right: 1px solid rgb(44, 131, 212);\n"
                                               "    border-bottom: 3px solid rgb(44, 131, 212);\n"
                                               "}\n"
                                               "QPushButton:pressed{\n"
                                               "    background-color: rgb(40, 170, 221);\n"
                                               "    border-left: 1px solid rgb(44, 131, 212);\n"
                                               "    border-right: 1px solid rgb(44, 131, 212);\n"
                                               "    border-top: 3px solid rgb(44, 131, 212);\n"
                                               "    border-bottomr: none;\n"
                                               "}\n"
                                               "")
        self.botonRegresarInicio.setObjectName("botonRegresarInicio")
        self.gridLayout.addWidget(self.botonRegresarInicio, 7, 3, 1, 1)
        self.labelNombreUsuario = QtWidgets.QLabel(IG2_MenuUsuario)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelNombreUsuario.setFont(font)
        self.labelNombreUsuario.setStyleSheet("font: 16pt \"Segoe Print\";\n"
                                              "color: rgb(0, 0, 0);")
        self.labelNombreUsuario.setObjectName("labelNombreUsuario")
        self.gridLayout.addWidget(self.labelNombreUsuario, 7, 0, 1, 1)
        self.labelBienvenida = QtWidgets.QLabel(IG2_MenuUsuario)
        self.labelBienvenida.setStyleSheet("font: 16pt \"Segoe Print\";")
        self.labelBienvenida.setObjectName("labelBienvenida")
        self.gridLayout.addWidget(self.labelBienvenida, 2, 0, 3, 1)
        self.botonModificarPerfil = QtWidgets.QPushButton(IG2_MenuUsuario)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botonModificarPerfil.setFont(font)
        self.botonModificarPerfil.setStyleSheet("QPushButton{\n"
                                                "color: rgb(255, 255, 255);\n"
                                                "    background-color: rgb(46, 165, 255);\n"
                                                "    font: 12pt \"Segoe Print\";\n"
                                                "    border-radius: 11px;\n"
                                                "    border:none;\n"
                                                "    border-left: 1px solid rgb(44, 131, 212);\n"
                                                "    border-right: 1px solid rgb(44, 131, 212);\n"
                                                "    border-bottom: 3px solid rgb(44, 131, 212);\n"
                                                "}\n"
                                                "QPushButton:hover{\n"
                                                "    background-color: rgb(14, 235, 255);\n"
                                                "    border-left: 1px solid rgb(44, 131, 212);\n"
                                                "    border-right: 1px solid rgb(44, 131, 212);\n"
                                                "    border-bottom: 3px solid rgb(44, 131, 212);\n"
                                                "}\n"
                                                "QPushButton:pressed{\n"
                                                "    background-color: rgb(40, 170, 221);\n"
                                                "    border-left: 1px solid rgb(44, 131, 212);\n"
                                                "    border-right: 1px solid rgb(44, 131, 212);\n"
                                                "    border-top: 3px solid rgb(44, 131, 212);\n"
                                                "    border-bottomr: none;\n"
                                                "}")
        self.botonModificarPerfil.setObjectName("botonModificarPerfil")
        self.gridLayout.addWidget(self.botonModificarPerfil, 6, 3, 1, 1)
        self.botonPracticar = QtWidgets.QPushButton(IG2_MenuUsuario)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botonPracticar.setFont(font)
        self.botonPracticar.setStyleSheet("QPushButton{\n"
                                          "color: rgb(255, 255, 255);\n"
                                          "    background-color: rgb(46, 165, 255);\n"
                                          "    font: 12pt \"Segoe Print\";\n"
                                          "    border-radius: 11px;\n"
                                          "    border:none;\n"
                                          "    border-left: 1px solid rgb(44, 131, 212);\n"
                                          "    border-right: 1px solid rgb(44, 131, 212);\n"
                                          "    border-bottom: 3px solid rgb(44, 131, 212);\n"
                                          "}\n"
                                          "QPushButton:hover{\n"
                                          "    background-color: rgb(14, 235, 255);\n"
                                          "    border-left: 1px solid rgb(44, 131, 212);\n"
                                          "    border-right: 1px solid rgb(44, 131, 212);\n"
                                          "    border-bottom: 3px solid rgb(44, 131, 212);\n"
                                          "}\n"
                                          "QPushButton:pressed{\n"
                                          "    background-color: rgb(40, 170, 221);\n"
                                          "    border-left: 1px solid rgb(44, 131, 212);\n"
                                          "    border-right: 1px solid rgb(44, 131, 212);\n"
                                          "    border-top: 3px solid rgb(44, 131, 212);\n"
                                          "    border-bottomr: none;\n"
                                          "}")
        self.botonPracticar.setObjectName("botonPracticar")
        self.gridLayout.addWidget(self.botonPracticar, 4, 3, 1, 1)

        self.Eventos(IG2_MenuUsuario)
        self.retranslateUi(IG2_MenuUsuario)
        QtCore.QMetaObject.connectSlotsByName(IG2_MenuUsuario)

    def Eventos(self,IG2_MenuUsuario):
        self.botonModificarPerfil.clicked.connect(lambda:self.abrirIG3(IG2_MenuUsuario))
        self.botonRegresarInicio.clicked.connect(lambda:self.abrirIG1(IG2_MenuUsuario))
        self.botonAprender.clicked.connect(lambda: self.abrirIG4(IG2_MenuUsuario))

    def abrirIG3(self,IG2_MenuUsuario):
        IG2_MenuUsuario.hide()
        self.IIG3=QtWidgets.QWidget()
        ui = G3.Ui_IG3_ModificacionPerfil()
        ui.setupUi(self.IIG3)
        self.IIG3.show()

    def abrirIG1(self,IG2_MenuUsuario):
        IG2_MenuUsuario.hide()
        self.IIG1=QtWidgets.QWidget()
        ui = G1.Ui_IG1_Bienvenida()
        ui.setupUi(self.IIG1)
        self.IIG1.show()

    def abrirIG4(self,IG2_MenuUsuario):
        IG2_MenuUsuario.hide()
        self.IIG4=QtWidgets.QWidget()
        ui = G4.Ui_IG4_Aprendizaje()
        ui.setupUi(self.IIG4)
        self.IIG4.show()

    def retranslateUi(self, IG2_MenuUsuario):
        _translate = QtCore.QCoreApplication.translate
        IG2_MenuUsuario.setWindowTitle(_translate("IG2_MenuUsuario", "Menú de usuario"))
        self.labelNombreUsuario.setText(_translate("IG2_MenuUsuario", self.nombreUsuario(1)))
        self.botonModificarPerfil.setText(_translate("IG2_MenuUsuario", "Modificar Perfil"))
        self.botonAprender.setText(_translate("IG2_MenuUsuario", "Aprender"))
        self.botonPracticar.setText(_translate("IG2_MenuUsuario", "Practicar"))
        self.botonRegresarInicio.setText(_translate("IG2_MenuUsuario", "Regresar a Inicio"))
        self.labelBienvenida.setText(_translate("IG2_MenuUsuario", "¡Que gusto verte!"))

    def nombreUsuario(self,id):
        usuario = Usuario()
        path = os.path.dirname(os.path.abspath(__file__)).replace("\\","/") + "/Clases/senas.db"
        usuario.setBD(path)
        usuario.obtenerUsuarioBDId(id)
        return usuario.nombre

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IG2_MenuUsuario = QtWidgets.QWidget()
    ui = Ui_IG2_MenuUsuario()
    ui.setupUi(IG2_MenuUsuario)
    IG2_MenuUsuario.show()
    app.exec_()
