# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IG5.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IG5_Sena(object):
    def setupUi(self, IG5_Sena):
        IG5_Sena.setObjectName("IG5_Sena")
        IG5_Sena.resize(865, 693)
        IG5_Sena.setStyleSheet("    background-color: rgb(255, 149, 250);\n"
"")
        self.widgetVideoTutorial = QtWidgets.QWidget(IG5_Sena)
        self.widgetVideoTutorial.setGeometry(QtCore.QRect(30, 50, 352, 640))
        self.widgetVideoTutorial.setObjectName("widgetVideoTutorial")
        self.botonReproducir = QtWidgets.QPushButton(IG5_Sena)
        self.botonReproducir.setGeometry(QtCore.QRect(470, 150, 101, 23))
        self.botonReproducir.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(46, 165, 255);\n"
"    font: 12pt \"Segoe Print\";\n"
"    border-radius: 11px;\n"
"    border:none;\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-bottom: 3px solid rgb(44, 131, 212);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(14, 235, 255);\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-bottom: 3px solid rgb(44, 131, 212);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(40, 170, 221);\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-top: 3px solid rgb(44, 131, 212);\n"
"    border-bottomr: none;\n"
"}")
        self.botonReproducir.setObjectName("botonReproducir")
        self.botonPausar = QtWidgets.QPushButton(IG5_Sena)
        self.botonPausar.setGeometry(QtCore.QRect(680, 150, 101, 23))
        self.botonPausar.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(46, 165, 255);\n"
"    font: 12pt \"Segoe Print\";\n"
"    border-radius: 11px;\n"
"    border:none;\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-bottom: 3px solid rgb(44, 131, 212);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(14, 235, 255);\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-bottom: 3px solid rgb(44, 131, 212);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(40, 170, 221);\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-top: 3px solid rgb(44, 131, 212);\n"
"    border-bottomr: none;\n"
"}")
        self.botonPausar.setObjectName("botonPausar")
        self.botonVerificar = QtWidgets.QPushButton(IG5_Sena)
        self.botonVerificar.setGeometry(QtCore.QRect(560, 450, 121, 23))
        self.botonVerificar.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(46, 165, 255);\n"
"    font: 12pt \"Segoe Print\";\n"
"    border-radius: 11px;\n"
"    border:none;\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-bottom: 3px solid rgb(44, 131, 212);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(14, 235, 255);\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-bottom: 3px solid rgb(44, 131, 212);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(40, 170, 221);\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-top: 3px solid rgb(44, 131, 212);\n"
"    border-bottomr: none;\n"
"}")
        self.botonVerificar.setObjectName("botonVerificar")
        self.labelTutorial = QtWidgets.QLabel(IG5_Sena)
        self.labelTutorial.setGeometry(QtCore.QRect(80, 10, 241, 31))
        self.labelTutorial.setStyleSheet("font: 16pt \"Segoe Print\";")
        self.labelTutorial.setObjectName("labelTutorial")
        self.lblCamara = QtWidgets.QLabel(IG5_Sena)
        self.lblCamara.setGeometry(QtCore.QRect(410, 320, 431, 291))
        self.lblCamara.setStyleSheet("border-color: rgb(0, 170, 0);")
        self.lblCamara.setMidLineWidth(-1)
        self.lblCamara.setText("")
        self.lblCamara.setWordWrap(False)
        self.lblCamara.setObjectName("lblCamara")
        self.botonSalir = QtWidgets.QPushButton(IG5_Sena)
        self.botonSalir.setGeometry(QtCore.QRect(740, 10, 121, 23))
        self.botonSalir.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(46, 165, 255);\n"
"    font: 12pt \"Segoe Print\";\n"
"    border-radius: 11px;\n"
"    border:none;\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-bottom: 3px solid rgb(44, 131, 212);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(14, 235, 255);\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-bottom: 3px solid rgb(44, 131, 212);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(40, 170, 221);\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-top: 3px solid rgb(44, 131, 212);\n"
"    border-bottomr: none;\n"
"}")
        self.botonSalir.setObjectName("botonSalir")
        self.lblSenaCorrecta = QtWidgets.QLabel(IG5_Sena)
        self.lblSenaCorrecta.setGeometry(QtCore.QRect(520, 250, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        self.lblSenaCorrecta.setFont(font)
        self.lblSenaCorrecta.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 11px;\n"
"border:none;\n"
"border-left: 1px solid  rgb(0, 85, 0);\n"
"border-right: 1px solid  rgb(0, 85, 0);\n"
"border-bottom: 3px solid  rgb(0, 85, 0);")
        self.lblSenaCorrecta.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSenaCorrecta.setObjectName("lblSenaCorrecta")
        self.lblCamara.raise_()
        self.widgetVideoTutorial.raise_()
        self.botonReproducir.raise_()
        self.botonPausar.raise_()
        self.botonVerificar.raise_()
        self.labelTutorial.raise_()
        self.botonSalir.raise_()
        self.lblSenaCorrecta.raise_()

        self.retranslateUi(IG5_Sena)
        QtCore.QMetaObject.connectSlotsByName(IG5_Sena)

    def retranslateUi(self, IG5_Sena):
        _translate = QtCore.QCoreApplication.translate
        IG5_Sena.setWindowTitle(_translate("IG5_Sena", "Form"))
        self.botonReproducir.setText(_translate("IG5_Sena", "Reproducir"))
        self.botonPausar.setText(_translate("IG5_Sena", "Pausar"))
        self.botonVerificar.setText(_translate("IG5_Sena", "Verificar seña"))
        self.labelTutorial.setText(_translate("IG5_Sena", "¿Cómo hacer la seña?"))
        self.botonSalir.setText(_translate("IG5_Sena", "Salir"))
        self.lblSenaCorrecta.setText(_translate("IG5_Sena", "Seña correcta "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IG5_Sena = QtWidgets.QWidget()
    ui = Ui_IG5_Sena()
    ui.setupUi(IG5_Sena)
    IG5_Sena.show()
    sys.exit(app.exec_())
