# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\IG7.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtMultimedia, QtMultimediaWidgets
from PyQt5.QtWidgets import QMessageBox
from Clases.Practica import Practica
from Clases.Senas import Senas
import IG6 as G6


class Ui_IG7_test(object):
	def setupUi(self, IG7_test):
		IG7_test.setObjectName("IG7_test")
		IG7_test.resize(1134, 611)
		IG7_test.setStyleSheet("QWidget{\n"
"background-color: rgb(250, 215, 160);\n"
"}\n"
"")
		self.boton_siguiente = QtWidgets.QPushButton(IG7_test)
		self.boton_siguiente.setGeometry(QtCore.QRect(470, 560, 151, 31))
		self.boton_siguiente.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(156, 100, 12);\n"
"    font: 12pt \"Segoe Print\";\n"
"    border-radius: 11px;\n"
"    border:none;\n"
"    border-left: 1px solid rgb(156, 100, 12);\n"
"    border-right: 1px solid rgb(156, 100, 12);\n"
"    border-bottom: 3px solid rgb(156, 100, 12);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(248, 196, 113);\n"
"    border-left: 1px solid rgb(248, 196, 113);\n"
"    border-right: 1px solid rgb(248, 196, 113);\n"
"    border-bottom: 3px solid rgb(248, 196, 113);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(40, 170, 221);\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-top: 3px solid rgb(44, 131, 212);\n"

"}")
		self.boton_siguiente.setObjectName("boton_siguiente")
		self.boton_opcion2_t1 = QtWidgets.QPushButton(IG7_test)
		self.boton_opcion2_t1.setGeometry(QtCore.QRect(800, 90, 245, 441))
		self.boton_opcion2_t1.setText("")
		self.boton_opcion2_t1.setObjectName("boton_opcion2_t1")
		self.boton_opcion1_t1 = QtWidgets.QPushButton(IG7_test)
		self.boton_opcion1_t1.setGeometry(QtCore.QRect(430, 90, 245, 441))
		self.boton_opcion1_t1.setText("")
		self.boton_opcion1_t1.setObjectName("boton_opcion1_t1")
		self.boton_opcion0_t1 = QtWidgets.QPushButton(IG7_test)
		self.boton_opcion0_t1.setGeometry(QtCore.QRect(60, 90, 245, 441))
		self.boton_opcion0_t1.setText("")
		self.boton_opcion0_t1.setObjectName("boton_opcion0_t1")
		self.label_instruccion = QtWidgets.QLabel(IG7_test)
		self.label_instruccion.setGeometry(QtCore.QRect(30, 30, 1071, 31))
		self.label_instruccion.setStyleSheet("font: 16pt \"Segoe Print\";\n"
"background-color: rgb(250, 215, 160);\n"
"color: rgb(156, 100, 12);\n"
"qproperty-alignment: AlignCenter;")
		self.label_instruccion.setObjectName("label_instruccion")
		self.widgetVideoTutorial = QtWidgets.QWidget(IG7_test)
		self.widgetVideoTutorial.setGeometry(QtCore.QRect(130, 90, 301, 441))
		self.widgetVideoTutorial.setObjectName("widgetVideoTutorial")
		self.boton_opcion1_t2 = QtWidgets.QPushButton(IG7_test)
		self.boton_opcion1_t2.setGeometry(QtCore.QRect(820, 220, 219, 31))
		self.boton_opcion1_t2.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(156, 100, 12);\n"
"    font: 12pt \"Segoe Print\";\n"
"    border-radius: 11px;\n"
"    border:none;\n"
"    border-left: 1px solid rgb(156, 100, 12);\n"
"    border-right: 1px solid rgb(156, 100, 12);\n"
"    border-bottom: 3px solid rgb(156, 100, 12);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(248, 196, 113);\n"
"    border-left: 1px solid rgb(248, 196, 113);\n"
"    border-right: 1px solid rgb(248, 196, 113);\n"
"    border-bottom: 3px solid rgb(248, 196, 113);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(40, 170, 221);\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-top: 3px solid rgb(44, 131, 212);\n"

"}")
		self.boton_opcion1_t2.setObjectName("boton_opcion1_t2")
		self.boton_opcion2_t2 = QtWidgets.QPushButton(IG7_test)
		self.boton_opcion2_t2.setGeometry(QtCore.QRect(660, 350, 219, 31))
		self.boton_opcion2_t2.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(156, 100, 12);\n"
"    font: 12pt \"Segoe Print\";\n"
"    border-radius: 11px;\n"
"    border:none;\n"
"    border-left: 1px solid rgb(156, 100, 12);\n"
"    border-right: 1px solid rgb(156, 100, 12);\n"
"    border-bottom: 3px solid rgb(156, 100, 12);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(248, 196, 113);\n"
"    border-left: 1px solid rgb(248, 196, 113);\n"
"    border-right: 1px solid rgb(248, 196, 113);\n"
"    border-bottom: 3px solid rgb(248, 196, 113);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(40, 170, 221);\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-top: 3px solid rgb(44, 131, 212);\n"

"}")
		self.boton_opcion2_t2.setObjectName("boton_opcion2_t2")
		self.boton_opcion0_t2 = QtWidgets.QPushButton(IG7_test)
		self.boton_opcion0_t2.setGeometry(QtCore.QRect(520, 220, 219, 31))
		self.boton_opcion0_t2.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(156, 100, 12);\n"
"    font: 12pt \"Segoe Print\";\n"
"    border-radius: 11px;\n"
"    border:none;\n"
"    border-left: 1px solid rgb(156, 100, 12);\n"
"    border-right: 1px solid rgb(156, 100, 12);\n"
"    border-bottom: 3px solid rgb(156, 100, 12);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(248, 196, 113);\n"
"    border-left: 1px solid rgb(248, 196, 113);\n"
"    border-right: 1px solid rgb(248, 196, 113);\n"
"    border-bottom: 3px solid rgb(248, 196, 113);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(40, 170, 221);\n"
"    border-left: 1px solid rgb(44, 131, 212);\n"
"    border-right: 1px solid rgb(44, 131, 212);\n"
"    border-top: 3px solid rgb(44, 131, 212);\n"

"}")
		self.boton_opcion0_t2.setObjectName("boton_opcion0_t2")

		#----------------#

		#setupVideo
		self.video = self.crearVideo(IG7_test)

		self.botones_opciones_t1 = [self.boton_opcion0_t1,self.boton_opcion1_t1,self.boton_opcion2_t1]
		self.botones_opciones_t2 = [self.boton_opcion0_t2,self.boton_opcion1_t2,self.boton_opcion2_t2]

		self.ocultarBotones()
		self.init()

		self.vistaRespuestas = 0
		self.opcionActiva = -1
		self.numPregunta = 0
		self.getPathMultimedia()
		self.mostrarPregunta(IG7_test)

		#----------------#
		self.retranslateUi(IG7_test)
		QtCore.QMetaObject.connectSlotsByName(IG7_test)

	def retranslateUi(self, IG7_test):
		_translate = QtCore.QCoreApplication.translate
		IG7_test.setWindowTitle(_translate("IG7_test", "Form"))
		self.boton_siguiente.setText(_translate("IG7_test", "Siguiente"))

	def setCuestionario(self,test):
		self.cuestionario = test

	def ocultarBotones(self):
		self.widgetVideoTutorial.setVisible(False)
		for i in range(3):
			self.botones_opciones_t1[i].setVisible(False)
			self.botones_opciones_t2[i].setVisible(False)

	def init(self):
		# Botones T1
		style = '''
			QPushButton{
				border: none;
				border-radius: 5px;
			}
			QPushButton:hover{
				border: 3px solid rgb(156, 100, 12);
			}
		'''
		for i in range(3):
			self.botones_opciones_t1[i].setStyleSheet(style)

		# Botones T2
		style = '''
			QPushButton{
				 color: rgb(255, 255, 255);
			    background-color: rgb(156, 100, 12);
			    font: 12pt \"Segoe Print\";
			    border-radius: 11px;
			    border:none;
			    border-left: 1px solid rgb(156, 100, 12);
			    border-right: 1px solid rgb(156, 100, 12);
			    border-bottom: 3px solid rgb(156, 100, 12);
			}
			QPushButton:hover{
			    background-color: rgb(248, 196, 113);
			    border-left: 1px solid rgb(248, 196, 113);
			    border-right: 1px solid rgb(248, 196, 113);
			    border-bottom: 3px solid rgb(248, 196, 113);
			}
		'''
		for i in range(3):
			self.botones_opciones_t2[i].setStyleSheet(style)
		self.opcionActiva = -1

	def mostrarPregunta(self,IG7_Test):
		if self.cuestionario.preguntas[self.numPregunta][0].tipo_sena == 0:	# Seña estatica
			sena = self.cuestionario.solucion[self.numPregunta]
			self.label_instruccion.setText("Selecciona la imagen correspondiente a la seña: " + sena.nombre_sena)
			for i in range(3):
				self.botones_opciones_t1[i].setVisible(True)
				self.imagenBoton(self.numPregunta)
		else: 															# Seña dinámica
			self.label_instruccion.setText("¿A cuál seña corresponde el video?")
			for i in range(3):
				self.botones_opciones_t2[i].setVisible(True)
			self.textoBotones()
			self.widgetVideoTutorial.setVisible(True)
			self.setupVideo(IG7_Test)

	def getPathMultimedia(self):
		self.pathMult = "videos/"
		if self.cuestionario.id_categoria == 1:
			self.pathMult += "abecedario/"
		if self.cuestionario.id_categoria == 2:
			self.pathMult += "numeros/"
		if self.cuestionario.id_categoria == 3:
			self.pathMult += "cuerpo/"
		if self.cuestionario.id_categoria == 4:
			self.pathMult += "dias/"
		if self.cuestionario.id_categoria == 5:
			self.pathMult += "colores/"

	# Vista señas estáticas
	def imagenBoton(self,indice):
		for i in range(3):
			sena = self.cuestionario.preguntas[indice][i]
			pixmap = QtGui.QPixmap(self.pathMult + f"{str(sena.nombre_sena)}.png")
			icon = QtGui.QIcon(pixmap)
			self.botones_opciones_t1[i].setIcon(icon)
			self.botones_opciones_t1[i].setIconSize(QtCore.QSize(300,435))

	def seleccionarOpcion_t1(self,opcion):
		style = '''
			QPushButton{
				border-radius: 5px;
				border: 3px solid  rgb(247, 197, 112);
			}
		'''
		self.init()
		self.opcionActiva = opcion
		self.botones_opciones_t1[opcion].setStyleSheet(style)
		# print(self.opcionActiva)

	# Vista señas dinámicas
	def textoBotones(self):
		for i in range(3):
			if self.vistaRespuestas == 1:
				style = '''
					QPushButton{
						background-color: rgb(19,207,73);
						color: rgb(255, 255, 255);
						font: 12pt \"Segoe Print\";
						border-radius: 11px;
						border:none;
						border-left: 1px solid rgb(18,151,56);;
						border-right: 1px solid rgb(18,151,56);
						border-bottom: 3px solid rgb(18,151,56);
					}
				'''
				self.botones_opciones_t2[i].setStyleSheet(style)
			sena = self.cuestionario.preguntas[self.numPregunta][i]
			self.botones_opciones_t2[i].setText(sena.nombre_sena.upper())

	def setupVideo(self, Form):
		sena = self.cuestionario.solucion[self.numPregunta]
		self.pathVideo = self.pathMult + f"{sena.nombre_sena.upper()}.wmv"
		self.video.show()
		self.contenedor = self.crearContenedor(Form)
		# self.contenedor.setMedia(QtMultimedia.QMediaContent(QtCore.QUrl(self.path)))
		self.playlist = QtMultimedia.QMediaPlaylist()
		self.playlist.setPlaybackMode(QtMultimedia.QMediaPlaylist.Loop)
		self.playlist.addMedia(QtMultimedia.QMediaContent(QtCore.QUrl(self.pathVideo)))
		self.contenedor.setPlaylist(self.playlist)
		self.contenedor.play()

	def crearContenedor(self, Form):
		contenedor = QtMultimedia.QMediaPlayer(Form)
		contenedor.setVideoOutput(self.video)
		return contenedor

	def crearVideo(self, Form):
		videoOutput = QtMultimediaWidgets.QVideoWidget(Form)
		caja = QtWidgets.QVBoxLayout()
		caja.addWidget(videoOutput)
		self.widgetVideoTutorial.setLayout(caja)
		return videoOutput

if __name__ == "__main__":
	import sys
	import os
	app = QtWidgets.QApplication(sys.argv)
	IG7_test = QtWidgets.QWidget()
	ui = Ui_IG7_test()

	cuestionario = Practica()
	path = os.path.dirname(os.path.abspath(__file__)).replace("\\","/") + "/Clases/senas.db"
	cuestionario.setBD(path)
	cuestionario.id_categoria = 5
	cuestionario.crearPreguntas()

	ui.setCuestionario(cuestionario)

	ui.setupUi(IG7_test)
	IG7_test.show()
	sys.exit(app.exec_())
