# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ventana2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import ventana1 as G1

class Ui_IG2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(411, 313)
        self.btn_CambiarVentana = QtWidgets.QPushButton(Form)
        self.btn_CambiarVentana.setGeometry(QtCore.QRect(130, 90, 141, 20))
        self.btn_CambiarVentana.setObjectName("pushButton_2")
        self.lbl_numVentana = QtWidgets.QLabel(Form)
        self.lbl_numVentana.setGeometry(QtCore.QRect(170, 190, 81, 16))
        self.lbl_numVentana.setObjectName("label_2")

        self.eventos(Form)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_CambiarVentana.setText(_translate("Form", "Ir a ventana 1"))
        self.lbl_numVentana.setText(_translate("Form", "Ventana 2"))

    def eventos(self,Form):
        self.btn_CambiarVentana.clicked.connect(lambda: self.cambiar_ventana(Form))

    def cambiar_ventana(self, Form):
        Form.close()
        self.IG1 = QtWidgets.QMainWindow()
        ui =  G1.Ui_IG1()
        ui.setupUi(self.IG1)
        self.IG1.show()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    IG2 = QtWidgets.QWidget()
    ui = Ui_IG2()
    ui.setupUi(IG2)
    IG2.show()
    app.exec_()