# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ventana1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import ventana2 as G2

class Ui_IG1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(325, 232)
        self.lbl_numVentana = QtWidgets.QLabel(Form)
        self.lbl_numVentana.setGeometry(QtCore.QRect(130, 50, 81, 16))
        self.lbl_numVentana.setObjectName("label")
        self.btn_cambiarVentana = QtWidgets.QPushButton(Form)
        self.btn_cambiarVentana.setGeometry(QtCore.QRect(80, 130, 141, 20))
        self.btn_cambiarVentana.setObjectName("pushButton")

        self.eventos(Form)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_numVentana.setText(_translate("Form", "Ventana 1"))
        self.btn_cambiarVentana.setText(_translate("Form", "Ir a ventana 2"))


    def eventos(self,Form):
        self.btn_cambiarVentana.clicked.connect(lambda: self.cambiar_ventana(Form))

    def cambiar_ventana(self, Form):
        Form.close()
        self.IG2 = QtWidgets.QMainWindow()
        ui =  G2.Ui_IG2()
        ui.setupUi(self.IG2)
        self.IG2.show()




if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    IG1 = QtWidgets.QWidget()
    ui = Ui_IG1()
    ui.setupUi(IG1)
    IG1.show()
    app.exec_()