# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IGP.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import IG4_1_Abecedario as abecedario
import IG4_2_Numeros as numeros
import IG4_3_Cuerpo as cuerpo
import IG4_4_Dias as dias
import IG4_5_Colores as colores
import IG2 as G2
from Clases.Usuario import Usuario
import os
from os import environ

class Ui_IG4_Aprendizaje(object):
    def setupUi(self, IG4_Aprendizaje):
        IG4_Aprendizaje.setObjectName("IG4_Aprendizaje")
        IG4_Aprendizaje.resize(950, 404)
        self.verticalLayout = QtWidgets.QVBoxLayout(IG4_Aprendizaje)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Tabs = QtWidgets.QTabWidget(IG4_Aprendizaje)
        self.Tabs.setObjectName("Tabs")
        self.tabInicio = QtWidgets.QWidget()
        self.tabInicio.setObjectName("tabInicio")
        self.labelBienvenida = QtWidgets.QLabel(self.tabInicio)
        self.labelBienvenida.setGeometry(QtCore.QRect(20, 80, 191, 16))
        self.labelBienvenida.setObjectName("labelBienvenida")
        self.labelInstrucciones = QtWidgets.QLabel(self.tabInicio)
        self.labelInstrucciones.setGeometry(QtCore.QRect(20, 90, 341, 61))
        self.labelInstrucciones.setObjectName("labelInstrucciones")
        self.labelNombreUsuario = QtWidgets.QLabel(self.tabInicio)
        self.labelNombreUsuario.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.labelNombreUsuario.setObjectName("labelNombreUsuario")
        self.botonRegresar = QtWidgets.QPushButton(self.tabInicio)
        self.botonRegresar.setGeometry(QtCore.QRect(250, 190, 75, 23))
        self.botonRegresar.setObjectName("botonRegresar")
        self.Tabs.addTab(self.tabInicio, "")

        self.tabAbecedario = QtWidgets.QWidget()
        self.tabAbecedario.setObjectName("tabAbecedario")
        self.widgetAbecedario = QtWidgets.QWidget(self.tabAbecedario)
        self.widgetAbecedario.setGeometry(QtCore.QRect(20, 10, 881, 311))
        self.widgetAbecedario.setObjectName("widgetAbecedario")
        ventanaAbecedario = abecedario.IG_Abecedario()
        ventanaAbecedario.iniciar_Abecedario(self.widgetAbecedario)
        ventanaAbecedario.retranslateUiAbecedario(IG4_Aprendizaje)
        self.Tabs.addTab(self.tabAbecedario, "")

        self.tabNumeros = QtWidgets.QWidget()
        self.tabNumeros.setObjectName("tabNumeros")
        self.widgetNumeros = QtWidgets.QWidget(self.tabNumeros)
        self.widgetNumeros.setGeometry(QtCore.QRect(30, 10, 881, 311))
        self.widgetNumeros.setObjectName("widgetNumeros")
        ventanaNumeros = numeros.IG_Numeros()
        ventanaNumeros.iniciar_Numeros(self.widgetNumeros)
        ventanaNumeros.retranslateUi(IG4_Aprendizaje)
        self.Tabs.addTab(self.tabNumeros, "")

        self.tabCuerpo = QtWidgets.QWidget()
        self.tabCuerpo.setObjectName("tabCuerpo")
        self.widgetCuerpo = QtWidgets.QWidget(self.tabCuerpo)
        self.widgetCuerpo.setGeometry(QtCore.QRect(30, 10, 784, 311))
        self.widgetCuerpo.setObjectName("widgetCuerpo")
        ventanaCuerpo = cuerpo.IG_Cuerpo()
        ventanaCuerpo.iniciar_Cuerpo(self.widgetCuerpo)
        ventanaCuerpo.retranslateUiCuerpo(IG4_Aprendizaje)
        self.Tabs.addTab(self.tabCuerpo, "")

        self.tabDias = QtWidgets.QWidget()
        self.tabDias.setObjectName("tabDias")
        self.widgetDias = QtWidgets.QWidget(self.tabDias)
        self.widgetDias.setGeometry(QtCore.QRect(80, 10, 784, 311))
        self.widgetDias.setObjectName("widgetDias")
        ventanaDias = dias.IG_Dias()
        ventanaDias.iniciar_Dias(self.widgetDias)
        ventanaDias.retranslateUiDias(IG4_Aprendizaje)
        #self.Tabs.addTab(self.tabDias, "") #Comentada porque tiene señas dinámicas

        self.tabColores = QtWidgets.QWidget()
        self.tabColores.setObjectName("tabColores")
        self.widgetColores = QtWidgets.QWidget(self.tabColores)
        self.widgetColores.setGeometry(QtCore.QRect(60, 10, 784, 311))
        self.widgetColores.setObjectName("widgetColores")
        ventanaColores = colores.IG_Colores()
        ventanaColores.iniciar_Colores(self.widgetColores)
        ventanaColores.retranslateUiColores(IG4_Aprendizaje)
        #self.Tabs.addTab(self.tabColores, "") #Comentada porque tiene señas dinámicas

        self.verticalLayout.addWidget(self.Tabs)
        self.Eventos(IG4_Aprendizaje)

        self.retranslateUi(IG4_Aprendizaje)
        self.Tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(IG4_Aprendizaje)

    def abrirIG2(self,IG4_Aprendizaje):
        IG4_Aprendizaje.hide()
        self.IIG2=QtWidgets.QWidget()
        ui=G2.Ui_IG2_MenuUsuario()
        ui.setupUi(self.IIG2)
        self.IIG2.show()
    def Eventos(self,IG4_Aprendizaje):
        self.botonRegresar.clicked.connect(lambda:self.abrirIG2(IG4_Aprendizaje))

    def nombreUsuario(self,id):
        usuario = Usuario()
        path = os.path.dirname(os.path.abspath(__file__)).replace("\\","/") + "/Clases/senas.db"
        usuario.setBD(path)
        usuario.obtenerUsuarioBDId(id)
        return usuario.nombre

    def retranslateUi(self, IG4_Aprendizaje):
        _translate = QtCore.QCoreApplication.translate
        IG4_Aprendizaje.setWindowTitle(_translate("IG4_Aprendizaje", "Form"))
        self.labelBienvenida.setText(_translate("IG4_Aprendizaje", "Bienvenido al menú de Aprendizaje"))
        self.labelInstrucciones.setText(_translate("IG4_Aprendizaje", "Presiona sobre una categoría para ver las señas disponibles"))
        self.labelNombreUsuario.setText(_translate("IG4_Aprendizaje", self.nombreUsuario(1)))
        self.botonRegresar.setText(_translate("IG4_Aprendizaje", "Regresar"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabInicio), _translate("IG4_Aprendizaje", "Inicio"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabAbecedario), _translate("IG4_Aprendizaje", "Abecedario"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabNumeros), _translate("IG4_Aprendizaje", "Números"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabCuerpo), _translate("IG4_Aprendizaje", "Cuerpo"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabDias), _translate("IG4_Aprendizaje", "Días"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tabColores), _translate("IG4_Aprendizaje", "Colores"))
def suppress_qt_warnings():
    environ["QT_DEVICE_PIXEL_RATIO"] = "0"
    environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
    environ["QT_SCREEN_SCALE_FACTORS"] = "1"
    environ["QT_SCALE_FACTOR"] = "1"

if __name__ == "__main__":
    import sys
    #suppress_qt_warnings()
    app = QtWidgets.QApplication(sys.argv)
    IG4_Aprendizaje = QtWidgets.QWidget()
    ui = Ui_IG4_Aprendizaje()
    ui.setupUi(IG4_Aprendizaje)
    IG4_Aprendizaje.show()
    sys.exit(app.exec_())
