# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IGP.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import IG4_1_Abecedario as abecedario
import IG4_2_Numeros as numeros
import IG2 as G2
from Clases.Usuario import Usuario
from os import environ

class Ui_IG4_Aprendizaje(object):
    def setupUi(self, IG4_Aprendizaje):
        IG4_Aprendizaje.setObjectName("IG4_Aprendizaje")
        IG4_Aprendizaje.resize(950, 404)
        self.verticalLayout = QtWidgets.QVBoxLayout(IG4_Aprendizaje)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs = QtWidgets.QTabWidget(IG4_Aprendizaje)
        self.tabs.setObjectName("tabs")
        self.tabInicio = QtWidgets.QWidget()
        self.tabInicio.setObjectName("tabInicio")
        self.labelBienvenida = QtWidgets.QLabel(self.tabInicio)
        self.labelBienvenida.setGeometry(QtCore.QRect(20, 80, 191, 16))
        self.labelBienvenida.setObjectName("labelBienvenida")
        self.labelInstrucciones = QtWidgets.QLabel(self.tabInicio)
        self.labelInstrucciones.setGeometry(QtCore.QRect(20, 90, 341, 61))
        self.labelInstrucciones.setObjectName("labelInstrucciones")
        self.labelNombreUsuario = QtWidgets.QLabel(self.tabInicio)
        self.labelNombreUsuario.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.labelNombreUsuario.setObjectName("labelNombreUsuario")
        self.botonRegresar = QtWidgets.QPushButton(self.tabInicio)
        self.botonRegresar.setGeometry(QtCore.QRect(250, 190, 75, 23))
        self.botonRegresar.setObjectName("botonRegresar")
        self.tabs.addTab(self.tabInicio, "")

        self.tabAbecedario = QtWidgets.QWidget()
        self.tabAbecedario.setObjectName("tabAbecedario")
        self.botonAbecedario = QtWidgets.QPushButton(self.tabAbecedario)
        self.botonAbecedario.setGeometry(QtCore.QRect(20, 10, 881, 23))
        self.botonAbecedario.setObjectName("botonAbecedario")
        self.widgetAbecedario = QtWidgets.QWidget(self.tabAbecedario)
        self.widgetAbecedario.setGeometry(QtCore.QRect(20, 30, 881, 311))
        self.widgetAbecedario.setObjectName("widgetAbecedario")
        ventanaAbecedario = abecedario.IG_Abecedario()
        ventanaAbecedario.iniciar_Abecedario(self.widgetAbecedario)
        ventanaAbecedario.retranslateUiAbecedario(IG4_Aprendizaje)
        self.tabs.addTab(self.tabAbecedario, "")

        self.tabNumeros = QtWidgets.QWidget()
        self.tabNumeros.setObjectName("tabNumeros")
        self.botonNumeros = QtWidgets.QPushButton(self.tabNumeros)
        self.botonNumeros.setGeometry(QtCore.QRect(30, 10, 881, 23))
        self.botonNumeros.setObjectName("botonNumeros")
        self.widgetNumeros = QtWidgets.QWidget(self.tabNumeros)
        self.widgetNumeros.setGeometry(QtCore.QRect(30, 30, 881, 311))
        self.widgetNumeros.setObjectName("widgetNumeros")
        ventanaNumeros = numeros.IG_Numeros()
        ventanaNumeros.iniciar_Numeros(self.widgetNumeros)
        ventanaNumeros.retranslateUi(IG4_Aprendizaje)
        self.tabs.addTab(self.tabNumeros, "")

        self.verticalLayout.addWidget(self.tabs)
        self.Eventos(IG4_Aprendizaje)

        self.retranslateUi(IG4_Aprendizaje)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(IG4_Aprendizaje)

    def abrirIG2(self,IG4_Aprendizaje):
        IG4_Aprendizaje.hide()
        self.IIG2=QtWidgets.QWidget()
        ui=G2.Ui_IG2_MenuUsuario()
        ui.setupUi(self.IIG2)
        self.IIG2.show()
    def Eventos(self,IG4_Aprendizaje):
        self.botonRegresar.clicked.connect(lambda:self.abrirIG2(IG4_Aprendizaje))

    def nombreUsuario(self, index):
        usuario = Usuario("")
        usuario.obtenerUsuarioIndex("usuarios.json", index)
        return usuario.nombre

    def retranslateUi(self, IG4_Aprendizaje):
        _translate = QtCore.QCoreApplication.translate
        IG4_Aprendizaje.setWindowTitle(_translate("IG4_Aprendizaje", "Form"))
        self.labelBienvenida.setText(_translate("IG4_Aprendizaje", "Bienvenido al menú de Aprendizaje"))
        self.labelInstrucciones.setText(_translate("IG4_Aprendizaje", "Presiona sobre una categoría para ver las señas disponibles"))
        self.labelNombreUsuario.setText(_translate("IG4_Aprendizaje", self.nombreUsuario(0)))
        self.botonRegresar.setText(_translate("IG4_Aprendizaje", "Regresar"))
        self.tabs.setTabText(self.tabs.indexOf(self.tabInicio), _translate("IG4_Aprendizaje", "Inicio"))
        self.botonAbecedario.setText(_translate("IG4_Aprendizaje", "Abecedario"))

        self.tabs.setTabText(self.tabs.indexOf(self.tabAbecedario), _translate("IG4_Aprendizaje", "Abecedario"))

        self.botonNumeros.setText(_translate("IG4_Aprendizaje", "Números"))
        self.tabs.setTabText(self.tabs.indexOf(self.tabNumeros), _translate("IG4_Aprendizaje", "Números"))

def suppress_qt_warnings():
    environ["QT_DEVICE_PIXEL_RATIO"] = "0"
    environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
    environ["QT_SCREEN_SCALE_FACTORS"] = "1"
    environ["QT_SCALE_FACTOR"] = "1"

if __name__ == "__main__":
    import sys
    suppress_qt_warnings()
    app = QtWidgets.QApplication(sys.argv)
    IG4_Aprendizaje = QtWidgets.QWidget()
    ui = Ui_IG4_Aprendizaje()
    ui.setupUi(IG4_Aprendizaje)
    IG4_Aprendizaje.show()
    sys.exit(app.exec_())
