from PyQt5 import QtCore, QtGui, QtWidgets
import IG5 as IGSena
import os


class IG_Colores(object):
    def iniciar_Colores(self,widgetColores):
        self.imagen_Amarillo = QtWidgets.QGraphicsView(widgetColores)
        self.imagen_Amarillo.setGeometry(QtCore.QRect(220, 20, 51, 41))
        self.imagen_Amarillo.setObjectName("imagen_Amarillo")
        self.boton_Amarillo = QtWidgets.QPushButton(widgetColores)
        self.boton_Amarillo.setGeometry(QtCore.QRect(210, 70, 75, 23))
        self.boton_Amarillo.setObjectName("boton_Amarillo")
        self.imagen_Azul = QtWidgets.QGraphicsView(widgetColores)
        self.imagen_Azul.setGeometry(QtCore.QRect(320, 20, 51, 41))
        self.imagen_Azul.setObjectName("imagen_Azul")
        self.boton_Azul = QtWidgets.QPushButton(widgetColores)
        self.boton_Azul.setGeometry(QtCore.QRect(310, 70, 75, 23))
        self.boton_Azul.setObjectName("boton_Azul")
        self.imagen_Blanco = QtWidgets.QGraphicsView(widgetColores)
        self.imagen_Blanco.setGeometry(QtCore.QRect(420, 20, 51, 41))
        self.imagen_Blanco.setObjectName("imagen_Blanco")
        self.boton_Blanco = QtWidgets.QPushButton(widgetColores)
        self.boton_Blanco.setGeometry(QtCore.QRect(410, 70, 75, 23))
        self.boton_Blanco.setObjectName("boton_Blanco")
        self.imagen_Cafe = QtWidgets.QGraphicsView(widgetColores)
        self.imagen_Cafe.setGeometry(QtCore.QRect(520, 20, 51, 41))
        self.imagen_Cafe.setObjectName("imagen_Cafe")
        self.boton_Cafe = QtWidgets.QPushButton(widgetColores)
        self.boton_Cafe.setGeometry(QtCore.QRect(510, 70, 75, 23))
        self.boton_Cafe.setObjectName("boton_Cafe")
        self.imagen_Rojo = QtWidgets.QGraphicsView(widgetColores)
        self.imagen_Rojo.setGeometry(QtCore.QRect(280, 220, 51, 41))
        self.imagen_Rojo.setObjectName("imagen_Rojo")
        self.boton_Rojo = QtWidgets.QPushButton(widgetColores)
        self.boton_Rojo.setGeometry(QtCore.QRect(270, 270, 75, 23))
        self.boton_Rojo.setObjectName("boton_Rojo")
        self.imagen_Gris = QtWidgets.QGraphicsView(widgetColores)
        self.imagen_Gris.setGeometry(QtCore.QRect(220, 120, 51, 41))
        self.imagen_Gris.setObjectName("imagen_Gris")
        self.boton_Gris = QtWidgets.QPushButton(widgetColores)
        self.boton_Gris.setGeometry(QtCore.QRect(210, 170, 75, 23))
        self.boton_Gris.setObjectName("boton_Gris")
        self.imagen_Morado = QtWidgets.QGraphicsView(widgetColores)
        self.imagen_Morado.setGeometry(QtCore.QRect(320, 120, 51, 41))
        self.imagen_Morado.setObjectName("imagen_Morado")
        self.boton_Morado = QtWidgets.QPushButton(widgetColores)
        self.boton_Morado.setGeometry(QtCore.QRect(310, 170, 75, 23))
        self.boton_Morado.setObjectName("boton_Morado")
        self.imagen_Naranja = QtWidgets.QGraphicsView(widgetColores)
        self.imagen_Naranja.setGeometry(QtCore.QRect(420, 120, 51, 41))
        self.imagen_Naranja.setObjectName("imagen_Naranja")
        self.boton_Naranja = QtWidgets.QPushButton(widgetColores)
        self.boton_Naranja.setGeometry(QtCore.QRect(410, 170, 75, 23))
        self.boton_Naranja.setObjectName("boton_Naranja")
        self.imagen_Negro = QtWidgets.QGraphicsView(widgetColores)
        self.imagen_Negro.setGeometry(QtCore.QRect(520, 120, 51, 41))
        self.imagen_Negro.setObjectName("imagen_Negro")
        self.boton_Negro = QtWidgets.QPushButton(widgetColores)
        self.boton_Negro.setGeometry(QtCore.QRect(510, 170, 75, 23))
        self.boton_Negro.setObjectName("boton_Negro")
        self.imagen_Verde = QtWidgets.QGraphicsView(widgetColores)
        self.imagen_Verde.setGeometry(QtCore.QRect(460, 220, 51, 41))
        self.imagen_Verde.setObjectName("imagen_Verde")
        self.boton_Verde = QtWidgets.QPushButton(widgetColores)
        self.boton_Verde.setGeometry(QtCore.QRect(450, 270, 75, 23))
        self.boton_Verde.setObjectName("boton_Verde")
        self.imagen_Rosa = QtWidgets.QGraphicsView(widgetColores)
        self.imagen_Rosa.setGeometry(QtCore.QRect(370, 220, 51, 41))
        self.imagen_Rosa.setObjectName("imagen_Rosa")
        self.boton_Rosa = QtWidgets.QPushButton(widgetColores)
        self.boton_Rosa.setGeometry(QtCore.QRect(360, 270, 75, 23))
        self.boton_Rosa.setObjectName("boton_Rosa")

        self.boton_Amarillo.clicked.connect(lambda: self.buttonClicked(self.boton_Amarillo))
        self.boton_Azul.clicked.connect(lambda: self.buttonClicked(self.boton_Azul))
        self.boton_Blanco.clicked.connect(lambda: self.buttonClicked(self.boton_Blanco))
        self.boton_Cafe.clicked.connect(lambda: self.buttonClicked(self.boton_Cafe))
        self.boton_Gris.clicked.connect(lambda: self.buttonClicked(self.boton_Gris))
        self.boton_Morado.clicked.connect(lambda: self.buttonClicked(self.boton_Morado))
        self.boton_Naranja.clicked.connect(lambda: self.buttonClicked(self.boton_Naranja))
        self.boton_Negro.clicked.connect(lambda: self.buttonClicked(self.boton_Negro))
        self.boton_Rojo.clicked.connect(lambda: self.buttonClicked(self.boton_Rojo))
        self.boton_Rosa.clicked.connect(lambda: self.buttonClicked(self.boton_Rosa))
        self.boton_Verde.clicked.connect(lambda: self.buttonClicked(self.boton_Verde))

    def buttonClicked(self, boton):
        self.IIG5=QtWidgets.QWidget()
        Sena = IGSena.Ui_IG5_Sena()
        Sena.setupUi(self.IIG5)
        Sena.setNombre(boton.text())
        ruta = ((os.path.dirname(os.path.abspath(__file__))).replace("\\","/") + "/videos/colores/")
        print(ruta)
        print(os.path.exists(ruta))
        ruta += boton.text() + ".wmv"
        print(os.path.exists(ruta))
        Sena.setPath(ruta)
        Sena.setup(self.IIG5)
        self.IIG5.show()
        #print(boton.text())
    def retranslateUiColores(self,IG4_Aprendizaje):
        _translate = QtCore.QCoreApplication.translate
        IG4_Aprendizaje.setWindowTitle(_translate("IG4_Aprendizaje", "Form"))
        self.boton_Amarillo.setText(_translate("IG4_Aprendizaje", "Amarillo"))
        self.boton_Azul.setText(_translate("IG4_Aprendizaje", "Azul"))
        self.boton_Blanco.setText(_translate("IG4_Aprendizaje", "Blanco"))
        self.boton_Cafe.setText(_translate("IG4_Aprendizaje", "Café"))
        self.boton_Rojo.setText(_translate("IG4_Aprendizaje", "Rojo"))
        self.boton_Gris.setText(_translate("IG4_Aprendizaje", "Gris"))
        self.boton_Morado.setText(_translate("IG4_Aprendizaje", "Morado"))
        self.boton_Naranja.setText(_translate("IG4_Aprendizaje", "Naranja"))
        self.boton_Negro.setText(_translate("IG4_Aprendizaje", "Negro"))
        self.boton_Verde.setText(_translate("IG4_Aprendizaje", "Verde"))
        self.boton_Rosa.setText(_translate("IG4_Aprendizaje", "Rosa"))