from PyQt5 import QtCore, QtGui, QtWidgets
import IG5 as IGSena

class IG_Numeros(object):
    def iniciar_Numeros(self,widgetNumeros):
        self.imagen_1 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_1.setGeometry(QtCore.QRect(30, 20, 51, 41))
        self.imagen_1.setObjectName("imagen_1")
        self.boton_1 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_1.setGeometry(QtCore.QRect(20, 70, 75, 23))
        self.boton_1.setObjectName("boton_1")
        self.imagen_2 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_2.setGeometry(QtCore.QRect(130, 20, 51, 41))
        self.imagen_2.setObjectName("imagen_2")
        self.boton_2 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_2.setGeometry(QtCore.QRect(120, 70, 75, 23))
        self.boton_2.setObjectName("boton_2")
        self.imagen_3 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_3.setGeometry(QtCore.QRect(220, 20, 51, 41))
        self.imagen_3.setObjectName("imagen_3")
        self.boton_3 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_3.setGeometry(QtCore.QRect(210, 70, 75, 23))
        self.boton_3.setObjectName("boton_3")
        self.imagen_4 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_4.setGeometry(QtCore.QRect(310, 20, 51, 41))
        self.imagen_4.setObjectName("imagen_4")
        self.boton_4 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_4.setGeometry(QtCore.QRect(300, 70, 75, 23))
        self.boton_4.setObjectName("boton_4")
        self.imagen_5 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_5.setGeometry(QtCore.QRect(410, 20, 51, 41))
        self.imagen_5.setObjectName("imagen_5")
        self.boton_5 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_5.setGeometry(QtCore.QRect(400, 70, 75, 23))
        self.boton_5.setObjectName("boton_5")
        self.imagen_6 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_6.setGeometry(QtCore.QRect(510, 20, 51, 41))
        self.imagen_6.setObjectName("imagen_6")
        self.boton_6 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_6.setGeometry(QtCore.QRect(500, 70, 75, 23))
        self.boton_6.setObjectName("boton_6")
        self.imagen_7 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_7.setGeometry(QtCore.QRect(610, 20, 51, 41))
        self.imagen_7.setObjectName("imagen_7")
        self.boton_7 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_7.setGeometry(QtCore.QRect(600, 70, 75, 23))
        self.boton_7.setObjectName("boton_7")
        self.imagen_8 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_8.setGeometry(QtCore.QRect(710, 20, 51, 41))
        self.imagen_8.setObjectName("imagen_8")
        self.boton_8 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_8.setGeometry(QtCore.QRect(700, 70, 75, 23))
        self.boton_8.setObjectName("boton_8")
        self.imagen_9 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_9.setGeometry(QtCore.QRect(810, 20, 51, 41))
        self.imagen_9.setObjectName("imagen_9")
        self.boton_9 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_9.setGeometry(QtCore.QRect(800, 70, 75, 23))
        self.boton_9.setObjectName("boton_9")
        self.imagen_10 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_10.setGeometry(QtCore.QRect(30, 120, 51, 41))
        self.imagen_10.setObjectName("imagen_10")
        self.boton_10 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_10.setGeometry(QtCore.QRect(20, 170, 75, 23))
        self.boton_10.setObjectName("boton_10")
        self.imagen_20 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_20.setGeometry(QtCore.QRect(130, 120, 51, 41))
        self.imagen_20.setObjectName("imagen_20")
        self.boton_20 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_20.setGeometry(QtCore.QRect(120, 170, 75, 23))
        self.boton_20.setObjectName("boton_20")
        self.imagen_30 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_30.setGeometry(QtCore.QRect(220, 120, 51, 41))
        self.imagen_30.setObjectName("imagen_30")
        self.boton_30 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_30.setGeometry(QtCore.QRect(210, 170, 75, 23))
        self.boton_30.setObjectName("boton_30")
        self.imagen_40 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_40.setGeometry(QtCore.QRect(310, 120, 51, 41))
        self.imagen_40.setObjectName("imagen_40")
        self.boton_40 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_40.setGeometry(QtCore.QRect(300, 170, 75, 23))
        self.boton_40.setObjectName("boton_40")
        self.imagen_50 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_50.setGeometry(QtCore.QRect(410, 120, 51, 41))
        self.imagen_50.setObjectName("imagen_50")
        self.boton_50 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_50.setGeometry(QtCore.QRect(400, 170, 75, 23))
        self.boton_50.setObjectName("boton_50")
        self.imagen_60 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_60.setGeometry(QtCore.QRect(510, 120, 51, 41))
        self.imagen_60.setObjectName("imagen_60")
        self.boton_60 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_60.setGeometry(QtCore.QRect(500, 170, 75, 23))
        self.boton_60.setObjectName("boton_60")
        self.imagen_70 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_70.setGeometry(QtCore.QRect(610, 120, 51, 41))
        self.imagen_70.setObjectName("imagen_70")
        self.boton_70 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_70.setGeometry(QtCore.QRect(600, 170, 75, 23))
        self.boton_70.setObjectName("boton_70")
        self.imagen_80 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_80.setGeometry(QtCore.QRect(710, 120, 51, 41))
        self.imagen_80.setObjectName("imagen_80")
        self.boton_80 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_80.setGeometry(QtCore.QRect(700, 170, 75, 23))
        self.boton_80.setObjectName("boton_80")
        self.imagen_90 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_90.setGeometry(QtCore.QRect(810, 120, 51, 41))
        self.imagen_90.setObjectName("imagen_90")
        self.boton_90 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_90.setGeometry(QtCore.QRect(800, 170, 75, 23))
        self.boton_90.setObjectName("boton_90")
        self.imagen_100 = QtWidgets.QGraphicsView(widgetNumeros)
        self.imagen_100.setGeometry(QtCore.QRect(410, 220, 51, 41))
        self.imagen_100.setObjectName("imagen_100")
        self.boton_100 = QtWidgets.QPushButton(widgetNumeros)
        self.boton_100.setGeometry(QtCore.QRect(400, 270, 75, 23))
        self.boton_100.setObjectName("boton_100")
        self.boton_1.clicked.connect(lambda: self.buttonClicked(self.boton_1))
        self.boton_2.clicked.connect(lambda: self.buttonClicked(self.boton_2))
        self.boton_3.clicked.connect(lambda: self.buttonClicked(self.boton_3))
        self.boton_4.clicked.connect(lambda: self.buttonClicked(self.boton_4))
        self.boton_5.clicked.connect(lambda: self.buttonClicked(self.boton_5))
        self.boton_6.clicked.connect(lambda: self.buttonClicked(self.boton_6))
        self.boton_7.clicked.connect(lambda: self.buttonClicked(self.boton_7))
        self.boton_8.clicked.connect(lambda: self.buttonClicked(self.boton_8))
        self.boton_9.clicked.connect(lambda: self.buttonClicked(self.boton_9))
        self.boton_10.clicked.connect(lambda: self.buttonClicked(self.boton_10))
        self.boton_20.clicked.connect(lambda: self.buttonClicked(self.boton_20))
        self.boton_30.clicked.connect(lambda: self.buttonClicked(self.boton_30))
        self.boton_40.clicked.connect(lambda: self.buttonClicked(self.boton_40))
        self.boton_50.clicked.connect(lambda: self.buttonClicked(self.boton_50))
        self.boton_60.clicked.connect(lambda: self.buttonClicked(self.boton_60))
        self.boton_70.clicked.connect(lambda: self.buttonClicked(self.boton_70))
        self.boton_80.clicked.connect(lambda: self.buttonClicked(self.boton_80))
        self.boton_90.clicked.connect(lambda: self.buttonClicked(self.boton_90))
        self.boton_100.clicked.connect(lambda: self.buttonClicked(self.boton_100))
    def buttonClicked(self, boton):
        self.IIG5=QtWidgets.QWidget()
        Sena = IGSena.Ui_IG5_Sena()
        Sena.setupUi(self.IIG5)
        Sena.setNombre(boton.text())
        self.IIG5.show()
    def retranslateUi(self, IG4_Aprendizaje):
        _translate = QtCore.QCoreApplication.translate
        IG4_Aprendizaje.setWindowTitle(_translate("IG4_Aprendizaje", "Form"))
        self.boton_1.setText(_translate("IG4_Aprendizaje", "1"))
        self.boton_2.setText(_translate("IG4_Aprendizaje", "2"))
        self.boton_3.setText(_translate("IG4_Aprendizaje", "3"))
        self.boton_4.setText(_translate("IG4_Aprendizaje", "4"))
        self.boton_5.setText(_translate("IG4_Aprendizaje", "5"))
        self.boton_6.setText(_translate("IG4_Aprendizaje", "6"))
        self.boton_7.setText(_translate("IG4_Aprendizaje", "7"))
        self.boton_8.setText(_translate("IG4_Aprendizaje", "8"))
        self.boton_9.setText(_translate("IG4_Aprendizaje", "9"))
        self.boton_10.setText(_translate("IG4_Aprendizaje", "10"))
        self.boton_20.setText(_translate("IG4_Aprendizaje", "20"))
        self.boton_30.setText(_translate("IG4_Aprendizaje", "30"))
        self.boton_40.setText(_translate("IG4_Aprendizaje", "40"))
        self.boton_50.setText(_translate("IG4_Aprendizaje", "50"))
        self.boton_60.setText(_translate("IG4_Aprendizaje", "60"))
        self.boton_70.setText(_translate("IG4_Aprendizaje", "70"))
        self.boton_80.setText(_translate("IG4_Aprendizaje", "80"))
        self.boton_90.setText(_translate("IG4_Aprendizaje", "90"))
        self.boton_100.setText(_translate("IG4_Aprendizaje", "100"))
