from PyQt5 import QtCore, QtGui, QtWidgets
import IG5 as IGSena
import os


class IG_Dias(object):
    def iniciar_Dias(self,widgetDias):
        self.imagen_Lunes = QtWidgets.QGraphicsView(widgetDias)
        self.imagen_Lunes.setGeometry(QtCore.QRect(250, 20, 51, 41))
        self.imagen_Lunes.setObjectName("imagen_Lunes")
        self.boton_Lunes = QtWidgets.QPushButton(widgetDias)
        self.boton_Lunes.setGeometry(QtCore.QRect(240, 70, 75, 23))
        self.boton_Lunes.setObjectName("boton_Lunes")
        self.imagen_Martes = QtWidgets.QGraphicsView(widgetDias)
        self.imagen_Martes.setGeometry(QtCore.QRect(350, 20, 51, 41))
        self.imagen_Martes.setObjectName("imagen_Martes")
        self.boton_Martes = QtWidgets.QPushButton(widgetDias)
        self.boton_Martes.setGeometry(QtCore.QRect(340, 70, 75, 23))
        self.boton_Martes.setObjectName("boton_Martes")
        self.imagen_Miercoles = QtWidgets.QGraphicsView(widgetDias)
        self.imagen_Miercoles.setGeometry(QtCore.QRect(450, 20, 51, 41))
        self.imagen_Miercoles.setObjectName("imagen_Miercoles")
        self.boton_Miercoles = QtWidgets.QPushButton(widgetDias)
        self.boton_Miercoles.setGeometry(QtCore.QRect(440, 70, 75, 23))
        self.boton_Miercoles.setObjectName("boton_Miercoles")
        self.imagen_Jueves = QtWidgets.QGraphicsView(widgetDias)
        self.imagen_Jueves.setGeometry(QtCore.QRect(300, 120, 51, 41))
        self.imagen_Jueves.setObjectName("imagen_Jueves")
        self.boton_Jueves = QtWidgets.QPushButton(widgetDias)
        self.boton_Jueves.setGeometry(QtCore.QRect(290, 170, 75, 23))
        self.boton_Jueves.setObjectName("boton_Jueves")
        self.imagen_Viernes = QtWidgets.QGraphicsView(widgetDias)
        self.imagen_Viernes.setGeometry(QtCore.QRect(400, 120, 51, 41))
        self.imagen_Viernes.setObjectName("imagen_Viernes")
        self.boton_Viernes = QtWidgets.QPushButton(widgetDias)
        self.boton_Viernes.setGeometry(QtCore.QRect(390, 170, 75, 23))
        self.boton_Viernes.setObjectName("boton_Viernes")
        self.imagen_Domingo = QtWidgets.QGraphicsView(widgetDias)
        self.imagen_Domingo.setGeometry(QtCore.QRect(390, 220, 51, 41))
        self.imagen_Domingo.setObjectName("imagen_Domingo")
        self.boton_Domingo = QtWidgets.QPushButton(widgetDias)
        self.boton_Domingo.setGeometry(QtCore.QRect(380, 270, 75, 23))
        self.boton_Domingo.setObjectName("boton_Domingo")
        self.imagen_Sabado = QtWidgets.QGraphicsView(widgetDias)
        self.imagen_Sabado.setGeometry(QtCore.QRect(300, 220, 51, 41))
        self.imagen_Sabado.setObjectName("imagen_Sabado")
        self.boton_Sabado = QtWidgets.QPushButton(widgetDias)
        self.boton_Sabado.setGeometry(QtCore.QRect(290, 270, 75, 23))
        self.boton_Sabado.setObjectName("boton_Sabado")

        self.boton_Domingo.clicked.connect(lambda : self.buttonClicked(self.boton_Domingo))
        self.boton_Lunes.clicked.connect(lambda: self.buttonClicked(self.boton_Lunes))
        self.boton_Martes.clicked.connect(lambda: self.buttonClicked(self.boton_Martes))
        self.boton_Miercoles.clicked.connect(lambda: self.buttonClicked(self.boton_Miercoles))
        self.boton_Jueves.clicked.connect(lambda: self.buttonClicked(self.boton_Jueves))
        self.boton_Viernes.clicked.connect(lambda: self.buttonClicked(self.boton_Viernes))
        self.boton_Sabado.clicked.connect(lambda: self.buttonClicked(self.boton_Sabado))
    def buttonClicked(self, boton):
        self.IIG5=QtWidgets.QWidget()
        Sena = IGSena.Ui_IG5_Sena()
        Sena.setupUi(self.IIG5)
        Sena.setNombre(boton.text())
        ruta = ((os.path.dirname(os.path.abspath(__file__))).replace("\\","/") + "/videos/abecedario/")
        print(ruta)
        print(os.path.exists(ruta))
        ruta += boton.text() + ".wmv"
        print(os.path.exists(ruta))
        Sena.setPath(ruta)
        Sena.setup(self.IIG5)
        self.IIG5.show()
        #print(boton.text())

    def retranslateUiDias(self,IG4_Aprendizaje):
        _translate = QtCore.QCoreApplication.translate
        IG4_Aprendizaje.setWindowTitle(_translate("IG4_Aprendizaje", "Form"))
        self.boton_Lunes.setText(_translate("IG4_Aprendizaje", "Lunes"))
        self.boton_Martes.setText(_translate("IG4_Aprendizaje", "Martes"))
        self.boton_Miercoles.setText(_translate("IG4_Aprendizaje", "Miércoles"))
        self.boton_Jueves.setText(_translate("IG4_Aprendizaje", "Jueves"))
        self.boton_Viernes.setText(_translate("IG4_Aprendizaje", "Viernes"))
        self.boton_Domingo.setText(_translate("IG4_Aprendizaje", "Domingo"))
        self.boton_Sabado.setText(_translate("IG4_Aprendizaje", "Sabado"))