# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IG1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import IG2 as G2
from Clases.Usuario import Usuario

class Ui_IG1_Bienvenida(object):
    def setupUi(self, IG1_Bienvenida):
        IG1_Bienvenida.setObjectName("IG1_Bienvenida")
        IG1_Bienvenida.resize(493, 348)
        IG1_Bienvenida.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonUsuario1 = QtWidgets.QPushButton(IG1_Bienvenida)
        self.botonUsuario1.setGeometry(QtCore.QRect(60, 110, 121, 41))
        self.botonUsuario1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonUsuario1.setObjectName("botonUsuario1")
        self.IUsuario1(IG1_Bienvenida)

        self.LabelBienvenida = QtWidgets.QLabel(IG1_Bienvenida)
        self.LabelBienvenida.setGeometry(QtCore.QRect(60, 40, 121, 21))
        self.LabelBienvenida.setObjectName("LabelBienvenida")

        self.retranslateUi(IG1_Bienvenida)
        QtCore.QMetaObject.connectSlotsByName(IG1_Bienvenida)

    def IUsuario1(self,IG1_Bienvenida):
        self.botonUsuario1.clicked.connect(lambda:self.abrirIG2(IG1_Bienvenida))
    def abrirIG2(self,IG1_Bienvenida):
        IG1_Bienvenida.hide()
        self.IIG2=QtWidgets.QWidget()
        ui = G2.Ui_IG2_MenuUsuario()
        ui.setupUi(self.IIG2)
        self.IIG2.show()

    def retranslateUi(self, IG1_Bienvenida):
        _translate = QtCore.QCoreApplication.translate
        IG1_Bienvenida.setWindowTitle(_translate("IG1_Bienvenida", "Form"))
        self.botonUsuario1.setText(_translate("IG1_Bienvenida", self.nombreUsuario(0)))
        self.LabelBienvenida.setText(_translate("IG1_Bienvenida", "Selecciona un usuario"))

    def nombreUsuario(self,index):
        usuario = Usuario("")
        usuario.obtenerUsuarioIndex("usuarios.json",index)
        return usuario.nombre

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IG1_Bienvenida = QtWidgets.QWidget()
    ui = Ui_IG1_Bienvenida()
    ui.setupUi(IG1_Bienvenida)
    IG1_Bienvenida.show()
    app.exec_()
