# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IG1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
from IG2 import *

class Ui_IG1(object):
    def setupUi(self, IG1):
        IG1.setObjectName("IG1")
        IG1.resize(486, 362)
        self.label = QtWidgets.QLabel(IG1)
        self.label.setGeometry(QtCore.QRect(50, 40, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.botonUsuario = QtWidgets.QPushButton(IG1)
        self.botonUsuario.setGeometry(QtCore.QRect(50, 210, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.botonUsuario.setFont(font)
        self.botonUsuario.setObjectName("botonUsuario")

        self.retranslateUi(IG1)
        QtCore.QMetaObject.connectSlotsByName(IG1)

        self.botonUsuario.clicked.connect(self.abrirUsuario)

    def retranslateUi(self, IG1):
        _translate = QtCore.QCoreApplication.translate
        IG1.setWindowTitle(_translate("IG1", "Form"))
        self.label.setText(_translate("IG1", "Selecciona un usuario"))
        self.botonUsuario.setText(_translate("IG1", "Usuario1"))

    def abrirVentana(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_IG2()
        self.ui.setupUi(self.window)
        IG1.hide()
        self.window.show()
    def abrirUsuario(self):
        self.abrirVentana()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IG1 = QtWidgets.QWidget()
    ui = Ui_IG1()
    ui.setupUi(IG1)
    IG1.show()
    sys.exit(app.exec_())
