# Form implementation generated from reading ui file 'IG1d.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Bienvenida(object):
    def setupUi(self, Bienvenida):
        Bienvenida.setObjectName("Bienvenida")
        Bienvenida.resize(800, 419)
        self.centralwidget = QtWidgets.QWidget(Bienvenida)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Usuario1 = QtWidgets.QPushButton(self.centralwidget)
        self.Usuario1.setGeometry(QtCore.QRect(10, 90, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(20)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.Usuario1.setFont(font)
        self.Usuario1.setObjectName("Usuario1")
        self.Usuario2 = QtWidgets.QPushButton(self.centralwidget)
        self.Usuario2.setGeometry(QtCore.QRect(10, 160, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(20)
        self.Usuario2.setFont(font)
        self.Usuario2.setObjectName("Usuario2")
        Bienvenida.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Bienvenida)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Bienvenida.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Bienvenida)
        self.statusbar.setObjectName("statusbar")
        Bienvenida.setStatusBar(self.statusbar)

        self.retranslateUi(Bienvenida)
        QtCore.QMetaObject.connectSlotsByName(Bienvenida)

    def retranslateUi(self, Bienvenida):
        _translate = QtCore.QCoreApplication.translate
        Bienvenida.setWindowTitle(_translate("Bienvenida", "MainWindow"))
        self.label.setText(_translate("Bienvenida", "Elige un perfil"))
        self.Usuario1.setText(_translate("Bienvenida", "Usuario1"))
        self.Usuario2.setText(_translate("Bienvenida", "Usuario2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bienvenida = QtWidgets.QMainWindow()
    ui = Ui_Bienvenida()
    ui.setupUi(Bienvenida)
    Bienvenida.show()
    sys.exit(app.exec())
