# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IG2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
from IG1 import *

class Ui_IG2(object):
    def setupUi(self, IG2):
        IG2.setObjectName("IG2")
        IG2.resize(490, 300)
        self.labelUsuario = QtWidgets.QLabel(IG2)
        self.labelUsuario.setGeometry(QtCore.QRect(60, 50, 47, 13))
        self.labelUsuario.setObjectName("labelUsuario")
        self.botonRegresarPerfiles = QtWidgets.QPushButton(IG2)
        self.botonRegresarPerfiles.setGeometry(QtCore.QRect(60, 150, 201, 41))
        self.botonRegresarPerfiles.setObjectName("botonRegresarPerfiles")

        self.retranslateUi(IG2)
        QtCore.QMetaObject.connectSlotsByName(IG2)

        self.botonRegresarPerfiles.clicked.connect(self.regresarPerfiles)
    def retranslateUi(self, IG2):
        _translate = QtCore.QCoreApplication.translate
        IG2.setWindowTitle(_translate("IG2", "Form"))
        self.labelUsuario.setText(_translate("IG2", "Usuario1"))
        self.botonRegresarPerfiles.setText(_translate("IG2", "Regresar a perfiles"))

    def abrirVentana(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_IG1()
        self.ui.setupUi(self.window)
        IG2.hide()
        self.window.show()
    def regresarPerfiles(self):
        self.abrirVentana()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IG2 = QtWidgets.QWidget()
    ui = Ui_IG2()
    ui.setupUi(IG2)
    IG2.show()
    sys.exit(app.exec_())
