# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IG2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import IG1 as G1
import IG3 as G3
class Ui_IG2_MenuUsuario(object):
    def setupUi(self, IG2_MenuUsuario):
        IG2_MenuUsuario.setObjectName("IG2_MenuUsuario")
        IG2_MenuUsuario.resize(495, 300)
        self.labelNombreUsuario = QtWidgets.QLabel(IG2_MenuUsuario)
        self.labelNombreUsuario.setGeometry(QtCore.QRect(50, 50, 61, 16))
        self.labelNombreUsuario.setObjectName("labelNombreUsuario")

        self.botonModificarPerfil = QtWidgets.QPushButton(IG2_MenuUsuario)
        self.botonModificarPerfil.setGeometry(QtCore.QRect(330, 50, 91, 21))
        self.botonModificarPerfil.setObjectName("botonModificarPerfil")
        self.ModificarPerfil(IG2_MenuUsuario)

        self.botonAprender = QtWidgets.QPushButton(IG2_MenuUsuario)
        self.botonAprender.setGeometry(QtCore.QRect(60, 130, 75, 23))
        self.botonAprender.setObjectName("botonAprender")
        self.botonPracticar = QtWidgets.QPushButton(IG2_MenuUsuario)
        self.botonPracticar.setGeometry(QtCore.QRect(260, 130, 75, 23))
        self.botonPracticar.setObjectName("botonPracticar")

        self.botonRegresarInicio = QtWidgets.QPushButton(IG2_MenuUsuario)
        self.botonRegresarInicio.setGeometry(QtCore.QRect(150, 230, 101, 23))
        self.botonRegresarInicio.setObjectName("botonRegresarInicio")
        self.regresarInicio(IG2_MenuUsuario)

        self.retranslateUi(IG2_MenuUsuario)
        QtCore.QMetaObject.connectSlotsByName(IG2_MenuUsuario)

    def ModificarPerfil(self,IG2_MenuUsuario):
        self.botonModificarPerfil.clicked.connect(lambda:self.abrirIG3(IG2_MenuUsuario))
    def abrirIG3(self,IG2_MenuUsuario):
        IG2_MenuUsuario.hide()
        self.IIG3=QtWidgets.QWidget()
        ui = G3.Ui_IG3_ModificacionPerfil()
        ui.setupUi(self.IIG3)
        self.IIG3.show()
    def regresarInicio(self, IG2_MenuUusuario):
        self.botonRegresarInicio.clicked.connect(lambda:self.abrirIG1(IG2_MenuUusuario))
    def abrirIG1(self,IG2_MenuUsuario):
        IG2_MenuUsuario.hide()
        self.IIG1=QtWidgets.QWidget()
        ui = G1.Ui_IG1_Bienvenida()
        ui.setupUi(self.IIG1)
        self.IIG1.show()

    def retranslateUi(self, IG2_MenuUsuario):
        _translate = QtCore.QCoreApplication.translate
        IG2_MenuUsuario.setWindowTitle(_translate("IG2_MenuUsuario", "Form"))
        self.labelNombreUsuario.setText(_translate("IG2_MenuUsuario", "Usuario1"))
        self.botonModificarPerfil.setText(_translate("IG2_MenuUsuario", "Modificar Perfil"))
        self.botonAprender.setText(_translate("IG2_MenuUsuario", "Aprender"))
        self.botonPracticar.setText(_translate("IG2_MenuUsuario", "Practicar"))
        self.botonRegresarInicio.setText(_translate("IG2_MenuUsuario", "Regresar a Inicio"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IG2_MenuUsuario = QtWidgets.QWidget()
    ui = Ui_IG2_MenuUsuario()
    ui.setupUi(IG2_MenuUsuario)
    IG2_MenuUsuario.show()
    app.exec_()
