# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IG4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import IG4_1_Abecedario as abecedario
import IG2 as G2
class Ui_IG4_Aprendizaje(object):
    def setupUi(self, IG4_Aprendizaje):
        IG4_Aprendizaje.setObjectName("IG4_Aprendizaje")
        IG4_Aprendizaje.resize(1038, 463)
        self.labelAprender = QtWidgets.QLabel(IG4_Aprendizaje)
        self.labelAprender.setGeometry(QtCore.QRect(40, 20, 47, 13))
        self.labelAprender.setObjectName("labelAprender")
        self.labelNombreUsuario = QtWidgets.QLabel(IG4_Aprendizaje)
        self.labelNombreUsuario.setGeometry(QtCore.QRect(380, 20, 47, 13))
        self.labelNombreUsuario.setObjectName("labelNombreUsuario")
        self.labelInstrucciones = QtWidgets.QLabel(IG4_Aprendizaje)
        self.labelInstrucciones.setGeometry(QtCore.QRect(40, 50, 321, 16))
        self.labelInstrucciones.setObjectName("labelInstrucciones")
        self.botonAbecedario = QtWidgets.QPushButton(IG4_Aprendizaje)
        self.botonAbecedario.setGeometry(QtCore.QRect(30, 110, 881, 23))
        self.botonAbecedario.setObjectName("botonAbecedario")

        self.widgetAbecedario = QtWidgets.QWidget(IG4_Aprendizaje)
        self.widgetAbecedario.setGeometry(QtCore.QRect(30, 130, 881, 311))
        self.widgetAbecedario.setObjectName("widgetAbecedario")
        ventanaAbecedario = abecedario.IG_Abecedario();
        ventanaAbecedario.iniciar_Abecedario(self.widgetAbecedario)
        ventanaAbecedario.retranslateUiAbecedario(IG4_Aprendizaje)

        self.botonRegresar = QtWidgets.QPushButton(IG4_Aprendizaje)
        self.botonRegresar.setGeometry(QtCore.QRect(40, 500, 75, 23))
        self.botonRegresar.setObjectName("botonRegresar")
        self.verticalScrollBar = QtWidgets.QScrollBar(IG4_Aprendizaje)
        self.verticalScrollBar.setGeometry(QtCore.QRect(1020, 0, 16, 551))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.Eventos(IG4_Aprendizaje)

        self.retranslateUi(IG4_Aprendizaje)
        QtCore.QMetaObject.connectSlotsByName(IG4_Aprendizaje)

    def abrirIG2(self,IG4_Aprendizaje):
        IG4_Aprendizaje.hide()
        self.IIG2=QtWidgets.QWidget()
        ui=G2.Ui_IG2_MenuUsuario()
        ui.setupUi(self.IIG2)
        self.IIG2.show()
    def Eventos(self,IG4_Aprendizaje):
        self.botonRegresar.clicked.connect(lambda:self.abrirIG2(IG4_Aprendizaje))

    def retranslateUi(self, IG4_Aprendizaje):
        _translate = QtCore.QCoreApplication.translate
        IG4_Aprendizaje.setWindowTitle(_translate("IG4_Aprendizaje", "Form"))
        self.labelAprender.setText(_translate("IG4_Aprendizaje", "Aprender"))
        self.labelNombreUsuario.setText(_translate("IG4_Aprendizaje", "Usuario1"))
        self.labelInstrucciones.setText(_translate("IG4_Aprendizaje", "Presiona sobre la categoría para visualizar la señas disponibles"))
        self.botonAbecedario.setText(_translate("IG4_Aprendizaje", "Abecedario"))
        self.botonRegresar.setText(_translate("IG4_Aprendizaje", "Regresar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IG4_Aprendizaje = QtWidgets.QWidget()
    ui = Ui_IG4_Aprendizaje()
    ui.setupUi(IG4_Aprendizaje)
    IG4_Aprendizaje.show()
    app.exec_()
